language: generic

matrix:
  include:
    - os: linux
      sudo: false
      env: CXX=g++-4.9 BUILDTYPE=Release
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-4.9', 'libstdc++-4.9-dev' ]
    - os: linux
      sudo: false
      env: CXX=g++-5 BUILDTYPE=Release
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-5', 'libstdc++-5-dev' ]
    - os: linux
      sudo: false
      env: CXX=clang++-3.9 BUILDTYPE=Release
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    # linux libc++ (vs libstdc++)
    - os: linux
      sudo: false
      env: CXX=clang++-3.9 BUILDTYPE=Release CXXFLAGS="-stdlib=libc++ -lc++ -lc++abi -lpthread -lrt -ldl"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      sudo: false
      env: CXX=clang++-3.9 BUILDTYPE=Debug CXXFLAGS="-stdlib=libc++ -lc++ -lc++abi -lpthread -lrt -ldl"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      sudo: false
      env: CXX=clang++-3.9 BUILDTYPE=Debug CXXFLAGS="-fsanitize=address"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: osx
      osx_image: xcode7.3

cache: apt

install:
  - | 
    if [[ ${CXX} =~ "clang" ]] && [[ $(uname -s) == "Linux" ]]; then
      mkdir ./mason
      curl -sSfL https://github.com/mapbox/mason/archive/v0.8.0.tar.gz | tar --gunzip --extract --strip-components=1 --exclude="*md" --exclude="test*" --directory=./mason
      ./mason/mason install clang++ 3.9.1
      export PATH=$(./mason/mason prefix clang++ 3.9.1)/bin:${PATH}
      which clang++
      ./mason/mason install binutils 2.27
      export PATH=$(./mason/mason prefix binutils 2.27)/bin:${PATH}
      which ld
    fi

script:
  - make test
  - make bench
  - make run-demo